version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1230
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/authdb
      JWT_SECRET: supersecretkey
    ports:
      - "3300:3300"
    depends_on:
      - db
    command: npm run dev
volumes:
  pgdata:
